{
 "title": "RebootMadDevice - Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "AreaName",
    "label": "AreaName",
    "query": {
     "query": "query_result(rmd_metric_area_quest_worker{})"
    }
   },
   {
    "name": "DeviceName",
    "label": "DeviceName",
    "query": {
     "query": "query_result(rmd_metric_device_info)"
    }
   },
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": {
     "query": "query_result(rmd_build_version_info)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Configuration",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rmd_metric_device_info{instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Devices",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*100/$B", "type": "math" }
   ]
  },
  {
   "title": "RMD Clients and Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rmd_build_version_info{instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Devices",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A*100/$B", "type": "math" }
   ]
  },
  {
   "title": "Reboots per device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(device) (rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reboots overall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "sum(rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"})",
     "legendFormat": "overall"
    }
   ]
  },
  {
   "title": "RMD Device Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rmd_metric_device_last_seen{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_forced_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_workstep{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_webhook_id{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}